### ISSUE TITLE
Please clean up your requirements.

### ISSUE THREAD

**Issue by amcgregor** [kevinadhiguna/body-mass-index-calculator#1]
Exactly the same problem as per: kevinadhiguna/link-shortener#1 and kevinadhiguna/instagram-profpic-downloader#1 … after a point this begins to get really spammy.

**Comment by kevinadhiguna** [comment]
Hi @amcgregor , I appreciate you for submitting this issue. It seems that this project does not need any additional packages. Thus, I removed `requirements.txt` in the [latest commit](https://github.com/kevinadhiguna/body-mass-index-calculator/commit/082f39496a0c826b23ce576fee4a5a9971b1dfe4). 

I hope the above is useful to you. Thank you once more for your help in this matter :)

**Comment by amcgregor** [comment]
Thank you very much, and apologies for the cross-project e-mail notification spam I must have triggered; thought you may wish to individually track corrections.

Thank you again! (Time for another spam-wave. 😭) ×2
